# Generated by Django 2.0 on 2019-12-16 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meiju',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('url', models.CharField(default='', max_length=255)),
                ('grade', models.CharField(default='', max_length=50)),
                ('imgurl', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
